### ISSUE TITLE
Adding description and changing the option name in Djanerio Templates to HTML

### ISSUE THREAD

**Issue by SoumyaRanjanNaik** [brmc/pycharm-djaneiro#5]
I would like to contribute to this project and make some changes to make this extension work better with the community edition so everyone can get the full features without any tweaking.

this snippet should change
```
<template name="autoescape" toReformat="true" toShortenFQNames="true" value="&#10;{% autoescape $VAR1$ %}&#10;&#9;$VAR2$$SELECTION}&#10;{% endautoescape %}&#10; $END$">
    <variable alwaysStopAt="true" defaultValue="&quot;&quot;" expression="" name="VAR2"/>
    <variable alwaysStopAt="true" defaultValue="&quot;off&quot;" expression="" name="VAR1"/>
    <context>
      <option name="Django" value="true"/>
    </context>
  </template>
```
to 
```
<template name="autoescape" toReformat="true" toShortenFQNames="true" value="&#10;{% autoescape $VAR1$ %}&#10;&#9;$VAR2$$SELECTION}&#10;{% endautoescape %}&#10; $END$">
    <variable alwaysStopAt="true" defaultValue="&quot;&quot;" expression="" name="VAR2"/>
    <variable alwaysStopAt="true" defaultValue="&quot;off&quot;" expression="" name="VAR1"/>
    <context>
      <option name="HTML" value="true"/>
    </context>
  </template>
```

**Comment by brmc** [comment]
Thanks for the interest. 

I agree it is too strict to only allow its usage in the Django context. 

I will have to update the project soon anyway because of a deprecated API in the jetbrains sdk. I will make this change then, but I can't say exactly when

If If you need it sooner than later, you can submit a pull request, but be aware I never update this repo by hand. I have another project that transpiles to the jetbrains format. You can find that project here: https://github.com/brmc/djaneiro-compiler

I never imagined anyone would use it, so it's not documented. You can look in this file to figure out how to use it: https://github.com/brmc/djaneiro-compiler/blob/master/transpile.py

It uses another library under the hood, and it's been so long since i've updated either, im not sure if they are still compatible with each other, so you might have to look here for more info: https://github.com/brmc/shortbus

**Comment by SoumyaRanjanNaik** [comment]
Would it be okay if i edited them by hand for now and could you compile and publish them as that would work as a temporary fix for this one.

Also I saw the code(though I am not that good at programming) of shortbus and i think you need to edit the `components.py` file's `SUBLIME_CONTENT_REGEX = r'\<\!\[CDATA\[(.*)\]\]'` because $SELECTION is being left out and not removed in the output and also we can fetch the descriptions as well as edit them with a prefix of Djanerio so it is easier for user to know which is the snippet he/she is looking for.

I would raise a PR soon in this repo(for a temporary fix) as well as for shortbus editing a few parts to fix the issues in shortbus please compile them as let me know if it worked as expected.
